# Plugin prefix:
Prefix: "&b&lQWaypoints &f&l> &r"

# Death points? true : false
DeathPoints: true

# Should public waypoints be available?
PublicWaypoints: true

trackers:
  enabled: true
  destination_reached: 10

  actionbar:
    enabled: true
    interval: 20
    indicatorcolor: "§b§l"
    leftarrow: "<-"
    rightarrow: "->"

  particle:
    enabled: true
    distance: 5


#     Config Version: ${project.version}    #