# Plugin prefix:
Prefix: "&b&lQWaypoints &f&l> &r"

# Death points? true : false
DeathPoints: true

# Should public waypoints be available?
PublicWaypoints: true

# This is regarding the member-to-member waypoint teleporting, admin teleporting is unaffected by this!
# Economy means vault-api support, it is a must for economy, along with an economy plugin for obvious reasons.
# Please note: Even if waypoint teleporting is enabled, players must have the qwaypoints.command.teleport permission for this to work for them.
WaypointTeleporting:
  enabled: false
  economy: false
  cost: 20

# Waypoint limits, replace dots with '-' instead
total_limits:
  "waypoints-limit-default": 10
  "waypoints-limit-vip": 15

# Configurations for all the trackers available
trackers:
  enabled: true
  destination_reached: 10

  actionbar:
    enabled: true
    interval: 20
    indicatorcolor: "§b§l"
    blockcolor: "§7"
    leftarrow: "<-"
    rightarrow: "->"

  particle:
    enabled: true
    length: 5
    heightOffset: 0
    particle: villager_happy
    amount: 15
    verticalDirection: false

  bossbar:
    enabled: true
    barcolor: BLUE

#     Config Version: ${project.version}    #