# Plugin prefix:
Prefix: "&b&lQWaypoints &f&l> &r"

# Death points? true : false
DeathPoints: true

# Should public waypoints be available?
PublicWaypoints: true



#     Config Version: 0.2-ALPHA1    #