name: QWaypoints
version: ${project.version}
main: me.yarinlevi.waypoints.Waypoints
api-version: 1.17
author: Quapi

commands:
  waypoint:
    description: Main command.
    aliases: [wp, qwaypoints, qwp]
  wpadmin:
    aliases: [wpa, waypointadmin, qwaypointadmin, wpadmin]
    permission: waypoints.admin